---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petstore-app
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: devops-n2-final
  path: "apps/petstore"
  prune: true
  targetNamespace: petstore
  wait: true